exec-once=systemctl --user start hyprpolkitagent 
exec-once=wl-paste --watch clipvault store --ignore-pattern '^<meta http-equiv='
exec-once=wl-paste --type image --watch clipvault store
exec-once=~/.config/scripts/waybar/waybar-force-restart.sh
exec-once=hyprsunset 
exec-once=swaync ## (or dunst) # notification daemon
exec-once=awww-daemon # wallpaper
exec-once=nu ~/.config/nushell/scripts/awww.nu init
exec-once=wl-paste --type text --watch cliphist store # clipboard
exec-once=wl-paste --type image --watch cliphist store
exec-once=kdeconnectd
exec-once=kdeconnect-indicator
exec-once=swayosd-server
exec-once=$terminal
exec-once=walker --gapplication-service
exec-once=kbuildsycoca6 ## package name kservice
