source=~/.config/hypr/rose-pine-moon.conf
source=~/.config/hypr/env.conf

$mainMod=SUPER
$terminal=foot
$fileManager=dolphin
$colorpicker=hyprpicker | wl-copy
$browser=zen
$notes=obsidian # TODO: use helix in notes folder
$menu=tofi-drun -c ~/.config/tofi/configA --drun-launch=true
$clipboard_copy=cliphist list | tofi -c ~/.config/tofi/configV | cliphist decode | wl-copy --trim-newline && hyprctl dispatch sendshortcut "CTRL SHIFT, V,"


source=~/.config/hypr/exec.conf
source=~/.config/hypr/monitors.conf
source=~/.config/hypr/window_rule.conf
source=~/.config/hypr/key_binding.conf


cursor {
  inactive_timeout=3
  no_hardware_cursors=true
}

general {
  layout=dwindle
  allow_tearing=false
  resize_on_border=true

  gaps_in=2
  gaps_out=2

  border_size=2
  col.active_border=$rose $pine $love $iris 90deg
  col.inactive_border=$muted
}

dwindle {
  preserve_split=true
  pseudotile=true
}

decoration {
  active_opacity=1.000000
  inactive_opacity=1.000000
  rounding=5

  blur {
    enabled=true
    ignore_opacity=true
    new_optimizations=true
    noise=0.000000
    passes=3
    size=4
    vibrancy=0.169600
  }
}

animations {
  bezier=wind, 0.05, 0.9, 0.1, 1.05
  bezier=winIn, 0.1, 1.1, 0.1, 1.1
  bezier=winOut, 0.3, -0.3, 0, 1
  bezier=liner, 1, 1, 1, 1
  animation=windows, 1, 6, wind, slide
  animation=windowsIn, 1, 6, winIn, slide
  animation=windowsOut, 1, 5, winOut, slide
  animation=windowsMove, 1, 5, wind, slide
  animation=border, 1, 1, liner
  animation=borderangle, 1, 30, liner, loop
  animation=fade, 1, 10, default
  animation=workspaces, 1, 1, wind
  enabled=true
}

input {
  kb_layout=us
  kb_options=caps:escape

  numlock_by_default=false
  sensitivity=0
  follow_mouse=1

  touchpad {
    natural_scroll=true
  }
}



misc {
  disable_hyprland_logo=true
  force_default_wallpaper=1
  vrr=0
}

# plugin {
#   dynamic-cursors {
#     rotate {
#       length=24
#       offset=0.000000
#     }

#     tilt {
#       function=negative_quadratic
#       limit=2000
#       window=50
#     }
#     enabled=false
#     mode=stretch
#     threshold=2
#   }

#   hyprcursor {
#     enabled=true
#     fallback=clientside
#     nearest=true
#     resolution=-1
#   }

#   shake {
#     base=4.000000
#     effects=true
#     enabled=true
#     influence=0.000000
#     ipc=true
#     limit=0.000000
#     nearest=true
#     speed=8.000000
#     threshold=3.000000
#     timeout=3000
#   }

#   stretch {
#     function=quadratic
#     limit=2000
#     window=50
#   }
# }

