layerrule {
  name = no_anim_for_launcher
  no_anim = on
  match:namespace = launcher
}

# windowrule = match:namespace launcher no_anim on
windowrule = match:namespace ie-r animation fade
windowrule = no_anim on, match:class ^(foot)$

# Window rules for HyprEmoji
windowrule = float true, match:title ^(HyprEmoji)$ 
windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.05)), match:title ^(HyprEmoji)$

windowrule {
  name = wiremix
  match:title = wiremix

  float = true
  center = true
}


windowrule = suppress_event maximize, match:class .*
windowrule = opacity 0.80 0.80, match:class ^(code-url-handler)$
windowrule = opacity 0.80 0.80, match:class ^(code-insiders-url-handler)$
windowrule = opacity 0.80 0.80, match:class ^(kitty)$
windowrule = opacity 0.80 0.80, match:class ^(org.gnome.Nautilus)$
windowrule = opacity 0.80 0.80, match:class ^(org.kde.ark)$
windowrule = opacity 0.80 0.80, match:class ^(nwg-look)$
windowrule = opacity 0.80 0.80, match:class ^(qt5ct)$
windowrule = opacity 0.80 0.80, match:class ^(qt6ct)$
windowrule = opacity 0.80 0.80, match:class ^(kvantummanager)$
windowrule = opacity 0.80 0.70, match:class ^(pavucontrol)$
windowrule = opacity 0.80 0.70, match:class ^(blueman-manager)$
windowrule = opacity 0.80 0.70, match:class ^(nm-applet)$
windowrule = opacity 0.70 0.70, match:class ^(Spotify)$
windowrule = opacity 0.70 0.70, match:initial_title ^(Spotify Free)$
windowrule = opacity 0.80 0.70, match:class ^(nm-connection-editor)$
windowrule = opacity 0.80 0.70, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = opacity 0.80 0.70, match:class ^(polkit-gnome-authentication-agent-1)$
windowrule = opacity 0.80 0.70, match:class ^(org.freedesktop.impl.portal.desktop.gtk)$
windowrule = opacity 0.80 0.70, match:class ^(org.freedesktop.impl.portal.desktop.hyprland)$
windowrule = match:float yes match:class ^(kvantummanager)$
windowrule = match:float yes match:class ^(qt5ct)$
windowrule = match:float yes match:class ^(qt6ct)$
windowrule = match:float yes match:class ^(nwg-look)$
windowrule = match:float yes match:class ^(org.kde.ark)$
windowrule = match:float yes match:class ^(pavucontrol)$
windowrule = match:float yes match:class ^(blueman-manager)$
windowrule = match:float yes match:class ^(nm-applet)$
windowrule = match:float yes match:class ^(nm-connection-editor)$
windowrule = match:float yes match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = match:float yes match:class ^(jome)$
windowrule = match:initial_title ^(Godot)$, float true


# windowrule = no_blur on, match:class ^(foot)$
# windowrule = opacity 1.0, match:fullscreen 1 match:class ^(foot)$
